# Generated by Django 4.0.4 on 2022-09-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventryapp', '0002_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myuser',
            new_name='Myusers',
        ),
        migrations.AlterModelTable(
            name='myusers',
            table='myusers',
        ),
    ]
