# Generated by Django 4.0.4 on 2022-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventryapp', '0003_rename_myuser_myusers_alter_myusers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='We',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'we',
            },
        ),
    ]
